from llava.constants import DEFAULT_IMAGE_TOKEN, IMAGE_TOKEN_INDEX, IGNORE_INDEX, DEFAULT_IM_START_TOKEN, DEFAULT_IM_END_TOKEN

IMAGE_TOKEN = DEFAULT_IMAGE_TOKEN
DEFAULT_POSE_TOKEN_INDEX = -300

# IMAGEA_TOKEN = '<imageA>'
# IMAGEB_TOKEN = '<imageB>'
CAPTION_TOKEN = '<caption>'
POSE_TOKEN = '<pose>'

# pose edit task
POSEA_TOKEN = '<poseA>'
POSEB_TOKEN = '<poseB>'
